version: '3.8'
services:
  keycloak:
    ports:
      - '8050:8080'
      - '8051:9000'
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_HOSTNAME: 'localhost'
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: 'true'
    volumes:
        - ./keycloak:/opt/keycloak/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"